# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from indy_driver/ServoTx.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ServoTx(genpy.Message):
  _md5sum = "a7e61d6578fded045ebf5ac1e96178fe"
  _type = "indy_driver/ServoTx"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string status_word
string mode_op_disp
int32 actual_pos
int32 actual_vel
int32 actual_tor
"""
  __slots__ = ['status_word','mode_op_disp','actual_pos','actual_vel','actual_tor']
  _slot_types = ['string','string','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       status_word,mode_op_disp,actual_pos,actual_vel,actual_tor

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ServoTx, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.status_word is None:
        self.status_word = ''
      if self.mode_op_disp is None:
        self.mode_op_disp = ''
      if self.actual_pos is None:
        self.actual_pos = 0
      if self.actual_vel is None:
        self.actual_vel = 0
      if self.actual_tor is None:
        self.actual_tor = 0
    else:
      self.status_word = ''
      self.mode_op_disp = ''
      self.actual_pos = 0
      self.actual_vel = 0
      self.actual_tor = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.status_word
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.mode_op_disp
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3i().pack(_x.actual_pos, _x.actual_vel, _x.actual_tor))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status_word = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status_word = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mode_op_disp = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.mode_op_disp = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.actual_pos, _x.actual_vel, _x.actual_tor,) = _get_struct_3i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.status_word
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.mode_op_disp
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3i().pack(_x.actual_pos, _x.actual_vel, _x.actual_tor))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status_word = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status_word = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mode_op_disp = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.mode_op_disp = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.actual_pos, _x.actual_vel, _x.actual_tor,) = _get_struct_3i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3i = None
def _get_struct_3i():
    global _struct_3i
    if _struct_3i is None:
        _struct_3i = struct.Struct("<3i")
    return _struct_3i
