# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from indy_driver/ServoDataArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import indy_driver.msg

class ServoDataArray(genpy.Message):
  _md5sum = "0442b85a27d0cc075ac423773b420d07"
  _type = "indy_driver/ServoDataArray"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """ServoTx[] tx
ServoRx[] rx

================================================================================
MSG: indy_driver/ServoTx
string status_word
string mode_op_disp
int32 actual_pos
int32 actual_vel
int32 actual_tor

================================================================================
MSG: indy_driver/ServoRx
int32 control_word
int32 mode_op
int32 target_pos
int32 target_vel
int32 target_tor"""
  __slots__ = ['tx','rx']
  _slot_types = ['indy_driver/ServoTx[]','indy_driver/ServoRx[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       tx,rx

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ServoDataArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.tx is None:
        self.tx = []
      if self.rx is None:
        self.rx = []
    else:
      self.tx = []
      self.rx = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.tx)
      buff.write(_struct_I.pack(length))
      for val1 in self.tx:
        _x = val1.status_word
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.mode_op_disp
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_3i().pack(_x.actual_pos, _x.actual_vel, _x.actual_tor))
      length = len(self.rx)
      buff.write(_struct_I.pack(length))
      for val1 in self.rx:
        _x = val1
        buff.write(_get_struct_5i().pack(_x.control_word, _x.mode_op, _x.target_pos, _x.target_vel, _x.target_tor))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.tx is None:
        self.tx = None
      if self.rx is None:
        self.rx = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.tx = []
      for i in range(0, length):
        val1 = indy_driver.msg.ServoTx()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.status_word = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.status_word = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.mode_op_disp = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.mode_op_disp = str[start:end]
        _x = val1
        start = end
        end += 12
        (_x.actual_pos, _x.actual_vel, _x.actual_tor,) = _get_struct_3i().unpack(str[start:end])
        self.tx.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.rx = []
      for i in range(0, length):
        val1 = indy_driver.msg.ServoRx()
        _x = val1
        start = end
        end += 20
        (_x.control_word, _x.mode_op, _x.target_pos, _x.target_vel, _x.target_tor,) = _get_struct_5i().unpack(str[start:end])
        self.rx.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.tx)
      buff.write(_struct_I.pack(length))
      for val1 in self.tx:
        _x = val1.status_word
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.mode_op_disp
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_3i().pack(_x.actual_pos, _x.actual_vel, _x.actual_tor))
      length = len(self.rx)
      buff.write(_struct_I.pack(length))
      for val1 in self.rx:
        _x = val1
        buff.write(_get_struct_5i().pack(_x.control_word, _x.mode_op, _x.target_pos, _x.target_vel, _x.target_tor))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.tx is None:
        self.tx = None
      if self.rx is None:
        self.rx = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.tx = []
      for i in range(0, length):
        val1 = indy_driver.msg.ServoTx()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.status_word = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.status_word = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.mode_op_disp = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.mode_op_disp = str[start:end]
        _x = val1
        start = end
        end += 12
        (_x.actual_pos, _x.actual_vel, _x.actual_tor,) = _get_struct_3i().unpack(str[start:end])
        self.tx.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.rx = []
      for i in range(0, length):
        val1 = indy_driver.msg.ServoRx()
        _x = val1
        start = end
        end += 20
        (_x.control_word, _x.mode_op, _x.target_pos, _x.target_vel, _x.target_tor,) = _get_struct_5i().unpack(str[start:end])
        self.rx.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3i = None
def _get_struct_3i():
    global _struct_3i
    if _struct_3i is None:
        _struct_3i = struct.Struct("<3i")
    return _struct_3i
_struct_5i = None
def _get_struct_5i():
    global _struct_5i
    if _struct_5i is None:
        _struct_5i = struct.Struct("<5i")
    return _struct_5i
