// Generated by gencpp from file indy_driver/IndyServiceRequest.msg
// DO NOT EDIT!


#ifndef INDY_DRIVER_MESSAGE_INDYSERVICEREQUEST_H
#define INDY_DRIVER_MESSAGE_INDYSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace indy_driver
{
template <class ContainerAllocator>
struct IndyServiceRequest_
{
  typedef IndyServiceRequest_<ContainerAllocator> Type;

  IndyServiceRequest_()
    : data(0)  {
    }
  IndyServiceRequest_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int32_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::indy_driver::IndyServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::indy_driver::IndyServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IndyServiceRequest_

typedef ::indy_driver::IndyServiceRequest_<std::allocator<void> > IndyServiceRequest;

typedef boost::shared_ptr< ::indy_driver::IndyServiceRequest > IndyServiceRequestPtr;
typedef boost::shared_ptr< ::indy_driver::IndyServiceRequest const> IndyServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::indy_driver::IndyServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::indy_driver::IndyServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::indy_driver::IndyServiceRequest_<ContainerAllocator1> & lhs, const ::indy_driver::IndyServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::indy_driver::IndyServiceRequest_<ContainerAllocator1> & lhs, const ::indy_driver::IndyServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace indy_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::indy_driver::IndyServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::indy_driver::IndyServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::indy_driver::IndyServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::indy_driver::IndyServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::indy_driver::IndyServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::indy_driver::IndyServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::indy_driver::IndyServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da5909fbe378aeaf85e547e830cc1bb7";
  }

  static const char* value(const ::indy_driver::IndyServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda5909fbe378aeafULL;
  static const uint64_t static_value2 = 0x85e547e830cc1bb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::indy_driver::IndyServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "indy_driver/IndyServiceRequest";
  }

  static const char* value(const ::indy_driver::IndyServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::indy_driver::IndyServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 data\n"
;
  }

  static const char* value(const ::indy_driver::IndyServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::indy_driver::IndyServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IndyServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::indy_driver::IndyServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::indy_driver::IndyServiceRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INDY_DRIVER_MESSAGE_INDYSERVICEREQUEST_H
