// Generated by gencpp from file indy_driver/IndyService.msg
// DO NOT EDIT!


#ifndef INDY_DRIVER_MESSAGE_INDYSERVICE_H
#define INDY_DRIVER_MESSAGE_INDYSERVICE_H

#include <ros/service_traits.h>


#include <indy_driver/IndyServiceRequest.h>
#include <indy_driver/IndyServiceResponse.h>


namespace indy_driver
{

struct IndyService
{

typedef IndyServiceRequest Request;
typedef IndyServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IndyService
} // namespace indy_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::indy_driver::IndyService > {
  static const char* value()
  {
    return "41a6318c88ca9d75d7a585e2aa4ca6ea";
  }

  static const char* value(const ::indy_driver::IndyService&) { return value(); }
};

template<>
struct DataType< ::indy_driver::IndyService > {
  static const char* value()
  {
    return "indy_driver/IndyService";
  }

  static const char* value(const ::indy_driver::IndyService&) { return value(); }
};


// service_traits::MD5Sum< ::indy_driver::IndyServiceRequest> should match
// service_traits::MD5Sum< ::indy_driver::IndyService >
template<>
struct MD5Sum< ::indy_driver::IndyServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::indy_driver::IndyService >::value();
  }
  static const char* value(const ::indy_driver::IndyServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::indy_driver::IndyServiceRequest> should match
// service_traits::DataType< ::indy_driver::IndyService >
template<>
struct DataType< ::indy_driver::IndyServiceRequest>
{
  static const char* value()
  {
    return DataType< ::indy_driver::IndyService >::value();
  }
  static const char* value(const ::indy_driver::IndyServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::indy_driver::IndyServiceResponse> should match
// service_traits::MD5Sum< ::indy_driver::IndyService >
template<>
struct MD5Sum< ::indy_driver::IndyServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::indy_driver::IndyService >::value();
  }
  static const char* value(const ::indy_driver::IndyServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::indy_driver::IndyServiceResponse> should match
// service_traits::DataType< ::indy_driver::IndyService >
template<>
struct DataType< ::indy_driver::IndyServiceResponse>
{
  static const char* value()
  {
    return DataType< ::indy_driver::IndyService >::value();
  }
  static const char* value(const ::indy_driver::IndyServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INDY_DRIVER_MESSAGE_INDYSERVICE_H
