// Generated by gencpp from file indy_driver/ServoDataArray.msg
// DO NOT EDIT!


#ifndef INDY_DRIVER_MESSAGE_SERVODATAARRAY_H
#define INDY_DRIVER_MESSAGE_SERVODATAARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <indy_driver/ServoTx.h>
#include <indy_driver/ServoRx.h>

namespace indy_driver
{
template <class ContainerAllocator>
struct ServoDataArray_
{
  typedef ServoDataArray_<ContainerAllocator> Type;

  ServoDataArray_()
    : tx()
    , rx()  {
    }
  ServoDataArray_(const ContainerAllocator& _alloc)
    : tx(_alloc)
    , rx(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::indy_driver::ServoTx_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::indy_driver::ServoTx_<ContainerAllocator> >> _tx_type;
  _tx_type tx;

   typedef std::vector< ::indy_driver::ServoRx_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::indy_driver::ServoRx_<ContainerAllocator> >> _rx_type;
  _rx_type rx;





  typedef boost::shared_ptr< ::indy_driver::ServoDataArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::indy_driver::ServoDataArray_<ContainerAllocator> const> ConstPtr;

}; // struct ServoDataArray_

typedef ::indy_driver::ServoDataArray_<std::allocator<void> > ServoDataArray;

typedef boost::shared_ptr< ::indy_driver::ServoDataArray > ServoDataArrayPtr;
typedef boost::shared_ptr< ::indy_driver::ServoDataArray const> ServoDataArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::indy_driver::ServoDataArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::indy_driver::ServoDataArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::indy_driver::ServoDataArray_<ContainerAllocator1> & lhs, const ::indy_driver::ServoDataArray_<ContainerAllocator2> & rhs)
{
  return lhs.tx == rhs.tx &&
    lhs.rx == rhs.rx;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::indy_driver::ServoDataArray_<ContainerAllocator1> & lhs, const ::indy_driver::ServoDataArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace indy_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::indy_driver::ServoDataArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::indy_driver::ServoDataArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::indy_driver::ServoDataArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::indy_driver::ServoDataArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::indy_driver::ServoDataArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::indy_driver::ServoDataArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::indy_driver::ServoDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0442b85a27d0cc075ac423773b420d07";
  }

  static const char* value(const ::indy_driver::ServoDataArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0442b85a27d0cc07ULL;
  static const uint64_t static_value2 = 0x5ac423773b420d07ULL;
};

template<class ContainerAllocator>
struct DataType< ::indy_driver::ServoDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "indy_driver/ServoDataArray";
  }

  static const char* value(const ::indy_driver::ServoDataArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::indy_driver::ServoDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ServoTx[] tx\n"
"ServoRx[] rx\n"
"\n"
"================================================================================\n"
"MSG: indy_driver/ServoTx\n"
"string status_word\n"
"string mode_op_disp\n"
"int32 actual_pos\n"
"int32 actual_vel\n"
"int32 actual_tor\n"
"\n"
"================================================================================\n"
"MSG: indy_driver/ServoRx\n"
"int32 control_word\n"
"int32 mode_op\n"
"int32 target_pos\n"
"int32 target_vel\n"
"int32 target_tor\n"
;
  }

  static const char* value(const ::indy_driver::ServoDataArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::indy_driver::ServoDataArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tx);
      stream.next(m.rx);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoDataArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::indy_driver::ServoDataArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::indy_driver::ServoDataArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "tx: ";
    if (v.tx.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.tx.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::indy_driver::ServoTx_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.tx[i]);
    }
    if (v.tx.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rx: ";
    if (v.rx.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.rx.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::indy_driver::ServoRx_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.rx[i]);
    }
    if (v.rx.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // INDY_DRIVER_MESSAGE_SERVODATAARRAY_H
