// Generated by gencpp from file indy_driver/ServoTx.msg
// DO NOT EDIT!


#ifndef INDY_DRIVER_MESSAGE_SERVOTX_H
#define INDY_DRIVER_MESSAGE_SERVOTX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace indy_driver
{
template <class ContainerAllocator>
struct ServoTx_
{
  typedef ServoTx_<ContainerAllocator> Type;

  ServoTx_()
    : status_word()
    , mode_op_disp()
    , actual_pos(0)
    , actual_vel(0)
    , actual_tor(0)  {
    }
  ServoTx_(const ContainerAllocator& _alloc)
    : status_word(_alloc)
    , mode_op_disp(_alloc)
    , actual_pos(0)
    , actual_vel(0)
    , actual_tor(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_word_type;
  _status_word_type status_word;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mode_op_disp_type;
  _mode_op_disp_type mode_op_disp;

   typedef int32_t _actual_pos_type;
  _actual_pos_type actual_pos;

   typedef int32_t _actual_vel_type;
  _actual_vel_type actual_vel;

   typedef int32_t _actual_tor_type;
  _actual_tor_type actual_tor;





  typedef boost::shared_ptr< ::indy_driver::ServoTx_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::indy_driver::ServoTx_<ContainerAllocator> const> ConstPtr;

}; // struct ServoTx_

typedef ::indy_driver::ServoTx_<std::allocator<void> > ServoTx;

typedef boost::shared_ptr< ::indy_driver::ServoTx > ServoTxPtr;
typedef boost::shared_ptr< ::indy_driver::ServoTx const> ServoTxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::indy_driver::ServoTx_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::indy_driver::ServoTx_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::indy_driver::ServoTx_<ContainerAllocator1> & lhs, const ::indy_driver::ServoTx_<ContainerAllocator2> & rhs)
{
  return lhs.status_word == rhs.status_word &&
    lhs.mode_op_disp == rhs.mode_op_disp &&
    lhs.actual_pos == rhs.actual_pos &&
    lhs.actual_vel == rhs.actual_vel &&
    lhs.actual_tor == rhs.actual_tor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::indy_driver::ServoTx_<ContainerAllocator1> & lhs, const ::indy_driver::ServoTx_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace indy_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::indy_driver::ServoTx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::indy_driver::ServoTx_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::indy_driver::ServoTx_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::indy_driver::ServoTx_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::indy_driver::ServoTx_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::indy_driver::ServoTx_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::indy_driver::ServoTx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7e61d6578fded045ebf5ac1e96178fe";
  }

  static const char* value(const ::indy_driver::ServoTx_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7e61d6578fded04ULL;
  static const uint64_t static_value2 = 0x5ebf5ac1e96178feULL;
};

template<class ContainerAllocator>
struct DataType< ::indy_driver::ServoTx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "indy_driver/ServoTx";
  }

  static const char* value(const ::indy_driver::ServoTx_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::indy_driver::ServoTx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string status_word\n"
"string mode_op_disp\n"
"int32 actual_pos\n"
"int32 actual_vel\n"
"int32 actual_tor\n"
;
  }

  static const char* value(const ::indy_driver::ServoTx_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::indy_driver::ServoTx_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status_word);
      stream.next(m.mode_op_disp);
      stream.next(m.actual_pos);
      stream.next(m.actual_vel);
      stream.next(m.actual_tor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoTx_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::indy_driver::ServoTx_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::indy_driver::ServoTx_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "status_word: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status_word);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode_op_disp: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mode_op_disp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "actual_pos: ";
    Printer<int32_t>::stream(s, indent + "  ", v.actual_pos);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "actual_vel: ";
    Printer<int32_t>::stream(s, indent + "  ", v.actual_vel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "actual_tor: ";
    Printer<int32_t>::stream(s, indent + "  ", v.actual_tor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INDY_DRIVER_MESSAGE_SERVOTX_H
