// Generated by gencpp from file indy_driver/ServoRx.msg
// DO NOT EDIT!


#ifndef INDY_DRIVER_MESSAGE_SERVORX_H
#define INDY_DRIVER_MESSAGE_SERVORX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace indy_driver
{
template <class ContainerAllocator>
struct ServoRx_
{
  typedef ServoRx_<ContainerAllocator> Type;

  ServoRx_()
    : control_word(0)
    , mode_op(0)
    , target_pos(0)
    , target_vel(0)
    , target_tor(0)  {
    }
  ServoRx_(const ContainerAllocator& _alloc)
    : control_word(0)
    , mode_op(0)
    , target_pos(0)
    , target_vel(0)
    , target_tor(0)  {
  (void)_alloc;
    }



   typedef int32_t _control_word_type;
  _control_word_type control_word;

   typedef int32_t _mode_op_type;
  _mode_op_type mode_op;

   typedef int32_t _target_pos_type;
  _target_pos_type target_pos;

   typedef int32_t _target_vel_type;
  _target_vel_type target_vel;

   typedef int32_t _target_tor_type;
  _target_tor_type target_tor;





  typedef boost::shared_ptr< ::indy_driver::ServoRx_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::indy_driver::ServoRx_<ContainerAllocator> const> ConstPtr;

}; // struct ServoRx_

typedef ::indy_driver::ServoRx_<std::allocator<void> > ServoRx;

typedef boost::shared_ptr< ::indy_driver::ServoRx > ServoRxPtr;
typedef boost::shared_ptr< ::indy_driver::ServoRx const> ServoRxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::indy_driver::ServoRx_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::indy_driver::ServoRx_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::indy_driver::ServoRx_<ContainerAllocator1> & lhs, const ::indy_driver::ServoRx_<ContainerAllocator2> & rhs)
{
  return lhs.control_word == rhs.control_word &&
    lhs.mode_op == rhs.mode_op &&
    lhs.target_pos == rhs.target_pos &&
    lhs.target_vel == rhs.target_vel &&
    lhs.target_tor == rhs.target_tor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::indy_driver::ServoRx_<ContainerAllocator1> & lhs, const ::indy_driver::ServoRx_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace indy_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::indy_driver::ServoRx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::indy_driver::ServoRx_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::indy_driver::ServoRx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::indy_driver::ServoRx_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::indy_driver::ServoRx_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::indy_driver::ServoRx_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::indy_driver::ServoRx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5c6b4ee5c2eed6b17a8e2ef1c7b6e65";
  }

  static const char* value(const ::indy_driver::ServoRx_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5c6b4ee5c2eed6bULL;
  static const uint64_t static_value2 = 0x17a8e2ef1c7b6e65ULL;
};

template<class ContainerAllocator>
struct DataType< ::indy_driver::ServoRx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "indy_driver/ServoRx";
  }

  static const char* value(const ::indy_driver::ServoRx_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::indy_driver::ServoRx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 control_word\n"
"int32 mode_op\n"
"int32 target_pos\n"
"int32 target_vel\n"
"int32 target_tor\n"
;
  }

  static const char* value(const ::indy_driver::ServoRx_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::indy_driver::ServoRx_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control_word);
      stream.next(m.mode_op);
      stream.next(m.target_pos);
      stream.next(m.target_vel);
      stream.next(m.target_tor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoRx_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::indy_driver::ServoRx_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::indy_driver::ServoRx_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "control_word: ";
    Printer<int32_t>::stream(s, indent + "  ", v.control_word);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode_op: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode_op);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_pos: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_pos);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_vel: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_vel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_tor: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_tor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INDY_DRIVER_MESSAGE_SERVORX_H
